version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Running Python script...
      - python main.py
      - zip -r app.zip main.py
artifacts:
  files:
    - app.zip
